# Generated by Django 4.1 on 2022-08-17 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heriage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arts_craft_post',
            name='image',
            field=models.ImageField(upload_to='heriage/craft'),
        ),
    ]
