# Generated by Django 4.1 on 2022-08-15 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist_profile',
            name='profile_type',
            field=models.CharField(blank=True, choices=[('select', '--select Profile--'), ('Personal', 'Personal'), ('Company', 'Company'), ('Orginization', 'Orginization'), ('Group', 'Group')], default='select', max_length=32),
        ),
    ]
