# Generated by Django 4.1 on 2022-08-15 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_artist_profile_pubcountry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist_profile',
            name='pubskills',
        ),
    ]
