# Generated by Django 4.1 on 2022-08-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_artist_profile_pubdocument_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist_profile',
            name='gender',
            field=models.CharField(choices=[('select', 'Select'), ('Male', 'Male'), ('Female', 'Female'), ('Others', 'Other')], default='select', max_length=32),
        ),
    ]
