# Generated by Django 4.1 on 2022-08-29 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_artist_profile_mail_alter_artist_profile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist_profile',
            name='pubmarital_status',
        ),
    ]
