# Generated by Django 4.1 on 2022-10-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_artist_profile_pubmarital_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='portfolios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=600)),
                ('image', models.ImageField(blank=True, null=True, upload_to='postimage/')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date_created')),
            ],
        ),
        migrations.AlterField(
            model_name='artist_profile',
            name='protfolio_image',
            field=models.FileField(blank=True, null=True, upload_to='protfolio'),
        ),
        migrations.AlterField(
            model_name='artist_profile',
            name='year_of_work',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
