# Generated by Django 4.0.6 on 2022-07-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addevent',
            name='profile',
        ),
        migrations.AddField(
            model_name='addevent',
            name='profile',
            field=models.ManyToManyField(default=1, to='app.artist_profile'),
        ),
    ]
