# Generated by Django 4.0.6 on 2022-07-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        ('event', '0002_remove_addevent_profile_addevent_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addevent',
            name='profile',
            field=models.ManyToManyField(default=[0], to='app.artist_profile'),
        ),
    ]
