# Generated by Django 4.0.6 on 2022-07-13 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_addevent_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addevent',
            name='profile',
        ),
    ]
