# Generated by Django 4.1 on 2022-08-15 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_remove_addevent_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addevent',
            old_name='Dzongkhag',
            new_name='dzongkhag',
        ),
        migrations.RenameField(
            model_name='addevent',
            old_name='medium',
            new_name='mediums',
        ),
    ]
