# Generated by Django 4.1 on 2022-08-15 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_rename_dzongkhag_addevent_dzongkhag_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addevent',
            old_name='discription',
            new_name='dis',
        ),
        migrations.RemoveField(
            model_name='addevent',
            name='available',
        ),
        migrations.RemoveField(
            model_name='addevent',
            name='dzongkhag',
        ),
        migrations.RemoveField(
            model_name='addevent',
            name='mediums',
        ),
    ]
