# Generated by Django 4.1 on 2022-08-17 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_rename_discription_addevent_dis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addevent',
            name='mail',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='addevent',
            name='phone',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
