# Generated by Django 4.1 on 2022-08-29 04:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_alter_addevent_mail_alter_addevent_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='addevent',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
