# Generated by Django 4.1 on 2022-08-29 05:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_addevent_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='addevent',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
