# Generated by Django 4.1 on 2022-09-06 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_addevent_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addevent',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='addevent',
            name='start_date',
            field=models.DateField(),
        ),
    ]
